/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 src/assets/ball.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function Ball(props) {
  const { nodes, materials } = useGLTF('/src/assets/ball.glb')
  const ref = useRef();
  useFrame((state, delta) => (
    ref.current.rotation.z += delta / 2,
    ref.current.rotation.x += delta / 2
  ))
  return (
    <group {...props} dispose={null}>
      <mesh ref={ref} geometry={nodes.Icosphere.geometry}>
        <meshLambertMaterial attach="material" color="#5B14A0" />
      </mesh>
    </group>
  )
}

useGLTF.preload('/ball.glb')
