/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 src/assets/box.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Box(props) {
  const { nodes, materials } = useGLTF("/src/assets/box.glb");
  const ref = useRef();
  useFrame(
    (state, delta) => (
      (ref.current.rotation.y += delta / 2),
      (ref.current.rotation.x += delta / 2)
    )
  );
  return (
    <group {...props} dispose={null}>
      <mesh ref={ref} geometry={nodes.Cube.geometry}>
        <meshLambertMaterial attach="material" color="#005AEF" />
      </mesh>
    </group>
  );
}

useGLTF.preload("/box.glb");
