/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 src/assets/computer.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Computer(props) {
  const { nodes, materials } = useGLTF('/src/assets/computer.glb');
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.computerScreen_2.geometry} material={materials.metalDark} />
      <mesh geometry={nodes.computerScreen_2_1.geometry} material={materials.metal} />
      <mesh geometry={nodes.computerScreen_3.geometry} material={materials.metal} />
      <mesh geometry={nodes.computerScreen_3_1.geometry} material={materials.metalDark} />
    </group>
  )
}

useGLTF.preload('/computer.glb')
