/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 src/assets/special.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Special(props) {
  const { nodes, materials } = useGLTF("/src/assets/special.glb");
  const ref = useRef();

  let columns = Math.floor(document.body.clientWidth / 50);
  let rows = Math.floor(document.body.clientHeight);

  useFrame(
    (state, delta) => (
      (ref.current.rotation.y += delta), (ref.current.rotation.x += delta)
    )
  );
  return (
    <group {...props} dispose={null}>
      <mesh ref={ref} geometry={nodes.Sphere.geometry}>
        <meshLambertMaterial attach="material" color="#5B14A0" />
      </mesh>
    </group>
  );
}

useGLTF.preload("/special.glb");
